This is makeindex, version 2.15 [TeX Live 2019] (kpathsea + Thai support).
Scanning style file ./hauptarbeit.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file hauptarbeit.acn....done (60 entries accepted, 0 rejected).
Sorting entries....done (380 comparisons).
Generating output file hauptarbeit.acr....done (42 lines written, 0 warnings).
Output written in hauptarbeit.acr.
Transcript written in hauptarbeit.alg.
